# Generated by Django 4.2.15 on 2024-08-28 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_brand_name_alter_product_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='model_name',
        ),
    ]
