# Generated by Django 4.2.15 on 2024-09-20 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_details',
            old_name='Age',
            new_name='age',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='Mobile_number',
        ),
        migrations.AddField(
            model_name='user_details',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user_details',
            name='mobile_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
